language: java
sudo: false
install: true

jdk:
  - oraclejdk8
  
before_script:
  - chmod +x runSonarQubeAnalysis.sh

script:
  - ./runSonarQubeAnalysis.sh

cache:
  directories:
    - '$HOME/.sonar/cache'
