FROM nginx
MAINTAINER Maciel Escudero Bombonato <maciel.bombonato@gmail.com>

ADD target/apolo-web-5.0.0/index.html /usr/share/nginx/html/index.html
ADD target/apolo-web-5.0.0/server /usr/share/nginx/html/server
ADD target/apolo-web-5.0.0/app /usr/share/nginx/html/app
ADD target/apolo-web-5.0.0/vendor /usr/share/nginx/html/vendor
